<?php echo '<?xml version="1.0" encoding="UTF-8" ?>';
      echo $this->doctype();
?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    
    <?php echo $this->headTitle(); ?>
    <link rel="icon" href="/images/favicon.ico" />
    <link rel="icon" href="/images/favicon_16x16.png" sizes="16x16" />
    <link rel="icon" href="/images/favicon_32x32.png" sizes="32x32" />
    <link rel="icon" href="/images/favicon_48x48.png" sizes="48x48" />
    
	<link href="/css/report.css" media="screen, print" rel="stylesheet" type="text/css" />
	<link href="/css/report-screen.css" media="screen" rel="stylesheet" type="text/css" />
</head>

<body>
<div class="report-wrapper">
<?php include "/include/report-header.php";?>

<div class="report-title">
	<h1>LAPORAN LABA/RUGI</h1>
	<h2>Periode <?php echo $this->tglAwal->get("dd/MM/yyyy"); ?> s/d <?php echo $this->tglAkhir->get("dd/MM/yyyy"); ?></h2>
</div>

<div class="report-body">
<table class="report report-no-border">
<tbody>
<?php $totalPendapatan = 0; $totalBiaya = 0; $totalPendNonOpr = 0; $totalBiayaNonOpr = 0; ?>

<?php $j = 0; foreach ($this->labarugi as $group): $j++; ?>
	
	<?php $i = 0; foreach ($group as $row): $i++; ?>
		<?php $margin = ($row["lvl"] * 20) + 3; $saldo = number_format($row["saldo"], 0); ?>
		
		<tr <?php if ($i == 1) echo 'style="border-top: 1px solid #000; "';?>>
		<?php if ($row["lvl"] >= 2): ?>
			<td style="padding-left: <?php echo $margin; ?>px; "><?php echo $row["account"]; ?></td>
			<td style="text-align: right; "><?php echo $saldo; ?></td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		
		<?php elseif ($row["lvl"] == 1 && $row["id"] == 0): ?>
			<td style="padding-left: <?php echo $margin; ?>px; font-weight: bold; "><?php echo $row["account"]; ?>:</td>
			<td style="border-top: 1px solid #000; ">&nbsp;</td>
			<td style="text-align: right; font-weight: bold; "><?php echo $saldo; ?></td>
			<td>&nbsp;</td>
		
		<?php elseif ($row["lvl"] == 1 && $row["isLeaf"]): ?>
			<td style="padding-left: <?php echo $margin; ?>px; "><?php echo $row["account"]; ?></td>
			<td>&nbsp;</td>
			<td style="text-align: right; "><?php echo $saldo; ?></td>
			<td>&nbsp;</td>
		
		<?php elseif ($row["lvl"] == 0 && $row["id"] == 0): ?>
			<td style="padding-left: <?php echo $margin; ?>px; font-weight: bold; "><?php echo $row["account"]; ?>:</td>
			<td>&nbsp;</td>
			<td style="border-top: 1px solid #000; ">&nbsp;</td>
			<td style="text-align: right;  font-weight: bold; "><?php echo $saldo; ?></td>
		
		<?php elseif ($row["lvl"] == 0 && $row["isLeaf"]): ?>
			<td style="padding-left: <?php echo $margin; ?>px; "><?php echo $row["account"]; ?></td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td style="text-align: right; "><?php echo $saldo; ?></td>
		
		<?php else: ?>
			<td style="padding-left: <?php echo $margin; ?>px; font-weight: bold; "><?php echo $row["account"]; ?></td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		<?php endif; ?>
		
		<?php switch ($j) {
			// TODO data seharusnya diambil hanya data terakhir per group sekali saja
			case 1: $totalPendapatan = $row["saldo"]; break;
			case 2: $totalBiaya = $row["saldo"]; break;
			case 3: $totalPendNonOpr = $row["saldo"]; break;
			case 4: $totalBiayaNonOpr = $row["saldo"]; break;
		} ?>
		</tr>
	<?php endforeach; ?>
	
	<?php if ($j == 2): ?>
		<tr style = "border-top: 2px solid #000; border-bottom: 2px solid #000; ">
			<td style="font-weight: bold; ">Pendapatan/Biaya:</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td style="text-align: right; font-weight: bold; "><?php echo number_format($totalPendapatan - $totalBiaya, 0); ?></td>
		</tr>
	<?php elseif ($j == 4): ?>
		<tr style = "border-top: 2px solid #000; border-bottom: 2px solid #000; ">
			<td style="font-weight: bold; ">Pendapatan/Biaya Non Operasional:</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td style="text-align: right; font-weight: bold; "><?php echo number_format($totalPendNonOpr - $totalBiayaNonOpr, 0); ?></td>
		</tr>
	<?php endif; ?>
<?php endforeach; ?>

<tr style = "border-top: 2px solid #000; border-bottom: 2px solid #000; ">
	<td style="font-weight: bold; ">Laba/Rugi:</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td style="text-align: right; font-weight: bold; "><?php echo number_format($totalPendapatan + $totalPendNonOpr - $totalBiaya - $totalBiayaNonOpr, 0); ?></td>
</tr>

</tbody>
</table>
</div>

<div class="report-footer">
	<div class="otorisasi">
		<div class="otorisasi-left">
			<div class="jabatan">Dibuat Oleh</div>
			<div class="nama"></div>
		</div>
		<div class="otorisasi-right">
			<div class="jabatan">Disetujui Oleh</div>
			<div class="nama"></div>
		</div>
		<div style="clear: both;"></div>
	</div>
</div>
</div>

</body>
</html>