<tr>
	<td class="action"><a class="delete" href="/account/delete/id/<?php echo $this->id; ?>"></a>
		<a class="update" href="/account/update/id/<?php echo $this->id; ?>"></a></td>
	<td><?php echo $this->kodeAccount; ?></td>
	<td style="padding-left: <?php echo ($this->depth * 20 + 3); ?>px"><?php echo $this->account; ?></td>
	<td style="text-align: center; "><?php echo $this->normalPosKet; ?></td>
	<td style="text-align: center; "><?php echo $this->kelompokKet; ?></td>
</tr>