<h1>An error occurred</h1>
<h2><?php echo $this->message ?></h2>

<?php if (isset($this->exception)): ?>

<h3>Exception information:</h3>
<p>
    <b>Message:</b> <span style="color: red; font-style: italic;"><?php echo $this->exception->getMessage() ?></span>
</p>

<h3>Stack trace:</h3>
<pre style="color: green;"><?php echo $this->exception->getTraceAsString() ?>
</pre>

<h3>Request Parameters:</h3>
<pre><?php echo var_export($this->request->getParams(), true) ?>
</pre>
<?php endif ?>