<script type="text/javascript"><!--
	var api;
	$(document).ready(function() {
		api = jQuery.Zend.jsonrpc({url: '/api/v1.0/jsonrpc.php', async: true });
		
		$(".form").validate({
			smd: api,
			functionName: "validateUserForm",
			toValidate: "#password",
			onSubmit: updatePassword
		});
	});

	/** Mengubah password user */
	var updatePassword = function() {
		api.updatePassword($("#id").val(), $("#password").val(), { success: function(result, id, method) {
			if (!result) {
				displayMessage("Data tidak dapat diubah!", "error");
				return;
			}
			
			window.location = "/user";
		}});
	};
//--></script>

<h1>Update Password <?php echo ($this->user)? $this->user->displayName: "User"; ?></h1>

<p>Masukkan password baru kemudian klik tombol simpan...</p>
<?php echo $this->form; ?>